# docker-compose.yml
services:
  mongo:
    build:
      context: ./mongodb_replica
      args:
        MONGO_VERSION: 6
    environment:
      MONGO_REPLICA_PORT: 27017
      MONGO_REPLICA_HOST: localhost
      MONGO_COMMAND: "mongosh"
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data
    restart: unless-stopped

  backend-dev:
    build:
      context: ../backend
      dockerfile: ../docker/backend/dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ../backend:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=mongodb://mongo:27017/growthX
    depends_on:
      - mongo
    restart: unless-stopped

  backend-prod:
    build:
      context: ../backend
      dockerfile: ../docker/backend/dockerfile.prod
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=mongodb://mongo:27017/growthX
    depends_on:
      - mongo
    restart: unless-stopped

volumes:
  mongo-data:
